shortname: director
domainname: servermain.local
stackhome: /home/stack
custom_templates: /home/stack/cloudConfig/heat/deployments/rhosp-16/templates-ovs-ml2

# Define the names of the source files that will be used to create
# to the destination system files instackenv.json and undercloud.conf
# respectively. If the role will be used on multiple sites then
# site names are encouraged. For example:
#
# instackenv-[SITE-NAME].sh
# undercloud-[SITE-NAME].conf

instackenv_sh: instackenv-servermain.sh
undercloud_conf: undercloud-servermain.conf

# Alternatively instackenv.json can be copied via template

# instackenv_json: instackenv-servermain.json
reg_script: files/addRepos-osp16.sh

# Deployment configuration, based on script
# Current values are:
# deploy-isolated-networks.sh | deploy-ovn.sh  
deploy_script: deploy-ovn.sh
