openstack quota set --cores -1 admin
openstack quota set --floating-ips -1 admin
openstack quota set --gigabytes -1 admin
openstack quota set --injected-file-size -1 admin
openstack quota set --injected-files -1 admin
openstack quota set --injected-path-size -1 admin
openstack quota set --instances -1 admin
openstack quota set --key-pairs -1 admin 
openstack quota set --networks -1 admin
openstack quota set --ports -1 admin
openstack quota set --properties -1 admin
openstack quota set --ram -1 admin
openstack quota set --rbac-policies -1 admin
openstack quota set --routers -1 admin
openstack quota set --secgroup-rules -1 admin
openstack quota set --secgroups -1 admin
openstack quota set --server-group-members -1 admin
openstack quota set --server-groups -1 admin
openstack quota set --snapshots -1 admin
openstack quota set --subnets -1 admin
openstack quota set --subnetpools -1 admin
openstack quota set --volumes -1 admin
