version: 1.0

name: osp15env-lab
description: >
  Default Deployment plan
template: overcloud.yaml
environments:
  - path: overcloud-resource-registry-puppet.yaml
  - path: environments/docker-ha.yaml
parameter_defaults:
  ControllerCount: 1
  ComputeCount: 1
  OvercloudComputeFlavor: baremetal
  OvercloudControllerFlavor: baremetal
